# Generated by Django 5.2.4 on 2025-07-18 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivarites_delete_chaibarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarites',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
