# Generated by Django 5.2.4 on 2025-07-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_chaivarites_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarites',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
