# Generated by Django 5.2.4 on 2025-07-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0006_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaicertificate',
            old_name='certificate',
            new_name='certificate_number',
        ),
    ]
